# Generated by Django 4.0.3 on 2022-04-12 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kohs', '0002_rename_name_profession_profession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kohperson',
            name='gender',
        ),
    ]
