# Generated by Django 4.0.3 on 2022-09-06 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kohs', '0006_passuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='kohPassword',
            fields=[
                ('url', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('passwd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kohs.passuser')),
            ],
        ),
    ]
